default_language_version:
    python: python3.12.3
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.2.2
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format
